### ISSUE TITLE
Unable to recognize new items updated in 1.21.*

### ISSUE THREAD

**Issue by CaesarGalahad** [HTTPStanley/DivinityEconomy#71]
Unable to recognize new items updated in 1.21.*
such as“BREEZE_ROD” ‘’wind_charge"

These items cannot be traded

INFO
DivinityEconomy version 3.5.3

**Comment by HTTPStanley** [comment]
HI @CaesarGalahad are these new items in 1.21?

I don't keep up with the game! Just this plugin :)

Can you try something for me?

Stop your server. Head to plugins > DivinityEconomy > materials.yml and add the following new entries:
```
BREEZE_ROD:
  ALLOWED: true
  MATERIAL_ID: BREEZE_ROD
  QUANTITY: 1696719
WIND_CHARGE:
  ALLOWED: true
  MATERIAL_ID: WIND_CHARGE
  QUANTITY: 878894
```
Start your server and try purchase `/buy BREEZE_ROD`

You can add friendly item names in materialAliases.yml in the following format:
`breezerod: BREEZE_ROD`
`windcharge: WIND_CHARGE`
